CREATE TABLE IF NOT EXISTS user_notifications (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  user_id VARCHAR(191) NOT NULL,
  title VARCHAR(191) NOT NULL,
  body VARCHAR(1024) NOT NULL,
  status VARCHAR(32) NOT NULL,
  error_message VARCHAR(1024) NULL,
  created_at_ms BIGINT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
